import { Platform } from "react-native";
import Constants from '../util/Constants';

module.exports = {
  MESSAGE: {
    STRING_ROOT_ACCESS_WARNING:
      Platform.OS === 'ios'
        ? 'Phone has been jail-broken. We found security vulnerability.'
        : 'Root access enable. We found security vulnerability.',
    NO_INTERNET: 'Please check your internet connectivity.',
    STRING_EMAIL_ID: 'Email',
    STRING_PASSWORD: 'Password',
    STRING_FORGOT_PASSWORD: 'Forgot password? ',
    STRING_LOGIN_BTN: 'Login',
    STRING_LOGOUT_BTN: 'Logout',
    STRING_RESET_PASSWORD_BTN: 'Reset password',
    NO_EMAIL_ID: 'Valid email id is required.',
    NO_PHONE_NUMBER: 'Valid phone number is required',
    NO_PASSWORD: 'Valid password is required.',
    SAME_PASSWORD: 'New and old password should not be same.',
    NO_OTP: 'Valid otp is required.',
    UPPER_CHARACTER: 'At least one upper character',
    LOWER_CHARACTER: 'At least one lower charcter',
    SPECIAL_CHARACTER: 'At least one special character',
    NUMBER_CHARACTER: 'At least one number',
    EIGHT_CHARACTER: 'At least 8 character',
    STRING_LOGOUT_ALERT: 'Do you want to logout?',
    STRING_WELCOME: 'Welcome',
    STRING_FORGOT_YOUR_PASSWORD: 'Forgot your password',
    STRING_PASSWORD_RESET: 'Password reset',
    STRING_SENT_EMAIL: 'We sent a code to',
    STRING_NO_WORRIES_MESSAGE: 'No worries, we\'ll send you reset instructions',
    STRING_EMAIL_VERIFED_MESSAGE: 'Your email has been verified.',
    STRING_UPDATE_PASSWORD_MESSAGE: 'Please update your password',
    STRING_CHANGE_PASSWORD_MESSAGE: 'Please change your password',
    STRING_CHANGE_PASSWORD: 'Change Password',
    STRING_UPDATE_PASSWORD: 'Update Password',
    STRING_OLD_PASSWORD: 'Old password',
    STRING_NEW_PASSWORD: 'New password',
    STRING_SIGNIN_MESSAGE: 'Login in to continue',
    SETTINGS_LOADING_TXT: 'Loading...',

    // API MESSAGES
    AUTH_FAILED: 'Email id and password you entered does not match.',
    UNABLE_CREATE_ACCOUNT: 'Unable to create account at this time. Try again.',
    UNABLE_SET_PASSWORD: 'Unable set password. Try again.',
    UNABLE_ADD_PAYMENT: 'Unable add you payment now. Try again.',
    EXPIRED: 'Session Expired.',
    REQ_FAILED: 'Unable to process the request. Please try again later.',
    WENT_WRONG: "We're working on it and we'll get it fixed as soon as we can.",
    USER_INACTIVE: 'User is inactive please contact support.',
    USER_NOT_FOUND: 'User not found. Please signup and then login.',
    LOGOUT_FAILED: 'Logout failed. Try again.',
    STRING_CHECK_NETWORK_HEADER: 'Check Network',
    STRING_NOT_NETWORK: 'Network not found',
    STRING_CHECK_NETWORK_MESSAGE: `It looks like you've lost your connection.`,
    STRING_EMPTY_MESSAGE: 'Looks like you haven\'t information.',

    STRING_IOS_UPDATE_MESSAGE:
      `There is a newer version of the ${Constants.APP_NAME} app available for download! Please update by visiting the App Store.`,
    STRING_ANDROID_UPDATE_MESSAGE:
      `There is a newer version of the ${Constants.APP_NAME} app available for download! Please update by visiting the Play Store.`,
    STRING_POWERED_BY: 'Powered by',
    CAMERA_LOADING_TXT: 'Camera Loading...',
    STRING_CAMERA_PERMISSION: 'Need camera permission to capture wheel',
    STRING_GRAND_ACCESS: 'Grand Access',

    // ADD YOUR STRINGS
    STRING_CAPTURE_WHEEEL: 'Capture Wheel',
    STRING_CAPTURE_WHEEEL_MSG: `Tap below to capture wheels`,
    STRING_FOR_CAPTURE_ADD_CODE_MSG: 'Look like you are not able to capture wheel without code. Please add code to capture wheel',
    STRING_FOR_CAPTURE_ADD_CODE_MSG_FOR_OPERATOR: 'Look like you are not able to capture wheel without code. Please contant your higher authority to add code',
    STRING_PALLET_DETAILS: 'Pallet Details',
    STRING_PALLET_ID: 'Pallet ID',
    STRING_SERIAL_CODE: 'Serial Code',
    STRING_PROCESSED_BY: 'Processed By',
    STRING_CAPTURED_WHEELS: 'Captured Wheels',


    // Employee screen
    EMPLOYEE_LIST: 'Employees',
    STRING_NO_STAFF_ERROR: 'No employee data',
    STRING_EMPTY_MESSAGE: 'Looks like you haven\'t information.',
    STRING_ADD_EMPLOYEE: 'Add Employee',
    STRING_EDIT_EMPLOYEE: 'Update Employee',
    STRING_EMPLOYEE_DETAILS: 'Employee Details',
    STRING_USERNAME: 'Full Name',
    STRING_NO_USERNAME: 'Please enter valid Full Name',
    STRING_EMP_ID: 'Employee ID',
    STRING_NO_EMP_ID: 'Please enter valid employee id',
    STRING_EMP_ID_LENGTH_ERROR: 'Employee ID must be at least 8 digits long.',
    STRING_CONTACT_NO: 'Contact No',
    STRING_NO_CONTACT_NO: 'Please enter valid contact number',
    STRING_ROLE: 'Role',
    STRING_NO_ROLE: 'Please select role',
    STRING_DELETE_EMPLOYEE: 'Delete Employee',
    STRING_AUTHENTICATION: 'Authentication Code',
    STRING_NO_AUTH: 'Please enter authentication code',
    STRING_ADD_SUCCESS_MSG: 'Employee onboarded successfully',
    STRING_UPDATE_SUCCESS_MSG: 'Employee updated successfully',
    STRING_DELETE_SUCCESS_MSG: 'Employee deleted successfully',

    // Code screen
    CODE_LIST: 'Codes',
    STRING_CODE: 'Code',
    STRING_NO_CODE_ERROR: 'No code data',
    STRING_NO_CODE: 'Please enter valid code',
    STRING_NO_CODE_SELECTED: 'Please select code',
    STRING_NO_PART_SELECTED: 'Please select part number',
    STRING_ADD_WHEEL_CODE: 'Add Wheel Code',
    STRING_EDIT_CODE: 'Update Wheel Code',
    STRING_CODE_DETAILS: 'Wheel Code Details',
    STRING_DELETE_CODE: 'Delete Code',
    STRING_NO_SELECT_COMPANY: 'Please select company',
    STRING_PALLET_LIMIT: 'Pallet Limit',
    STRING_NO_PALLET_LIMIT: 'Please enter valid pallet limit',
    STRING_PART_NUM: 'Part Number',
    STRING_NO_PART_NUMBER: 'Please enter valid part number',
    STRING_CODE_ADD_SUCCESS_MSG: 'Wheel code added successfully',
    STRING_CODE_UPDATE_SUCCESS_MSG: 'Wheel code updated successfully',
    STRING_CODE_DELETE_SUCCESS_MSG: 'Wheel code deleted successfully',

    // Company screen
    COMPANY_LIST: 'Companies',
    STRING_COMPANY: 'Company',
    STRING_COMPANY_NOT_FOUND: 'Company not found',
    STRING_NO_COMPANY: 'Please enter valid company name',
    STRING_ADD_COMPANY: 'Add Company',
    STRING_EDIT_COMPANY: 'Update Company',
    STRING_DELETE_COMPANY: 'Delete Code',
    STRING_ADD_SUSSESS_MSG: 'Company name added successfully',
    STRING_UPDATE_SUSSESS_MSG: 'Company name updated successfully',
    STRING_DELETE_SUSSESS_MSG: 'Company deleted successfully',

    // Wheel screen
    WHEEL_LIST: 'Wheels',
    STRING_WHEEL: 'Wheel',
    STRING_NO_WHEEL_ERROR: 'No wheel data',
    STRING_NO_WHEEL: 'Please enter valid wheel',
    STRING_ADD_WHEEL: 'Add Wheel',
    STRING_EDIT_WHEEL: 'Update Wheel',
    STRING_DELETE_WHEEL: 'Delete Wheel',
    STRING_CAPTURED_WHEEL: 'Captured Wheel',
    STRING_EDIT_WHEEL_SUCCESS_MSG: 'Wheels edited successfully',
    STRING_DELETE_WHEEL_SUCCESS_MSG: 'Wheels deleted successfully',

    // Notification screen
    NOTIFICATION_LIST: 'Notification',
    STRING_ACTIVE: 'Active',
    STRING_RESOLVED: 'Resolved',
    STRING_NO_ACTIVE_NOTIFICATION_ERROR: 'No active notification data',
    STRING_NO_RESOLVED_NOTIFICATION_ERROR: 'No resolved notification data',
    STRING_DELETE_NOTIFICATION: 'Delete Notification',
    STRING_WRONG_WHEEL_DETECTED: 'Wrong wheel detected',

    // Pallet screen
    PALLET_LIST: 'Pallets',
    STRING_DELETE_PALLET: 'Delete Pallet',
    STRING_NO_PALLET_ERROR: 'No pallet data',
    STRING_CAPTURED_WHEEL: 'Captured Wheel',
    STRING_DELETE_PALLET_SUCCESS_MSG: 'Pallet deleted successfully',

    STRING_CREATED_BY: 'Created By',
    STRING_UPDATED_BY: 'Updated By',
    STRING_RESOLVED_BY: 'Resolved By',
    STRING_CAPTURE_WHEEL: 'Capture Wheel',

    // BLUTOOTH
    STRING_AVAILABLE_DEVICES: 'Available Devices',
    STRING_SCAN: 'Scan',
    STRING_DEVICES: 'Devices',
    STRING_UNPAIR: 'Unpair',
    STRING_CONNECTED: 'Connected',
    STRING_DISCONNECTED: 'Disconnected',
    STRING_PRINT: 'Print',
    STRING_PAIRED_DEVICES: 'Paired Devices',

    // Barcode
    STRING_BARCODE_CAMERA_PERMISSION: 'Need camera permission for barcode scan',

    // SWIFT DETAILS,
    STRING_SWIFT_DETAILS: 'Update Shift Details',
    STRING_INSPECTOR_ONE: 'Inspector 1',
    STRING_INSPECTOR_TWO: 'Inspector 2',
    STRING_INSPECTOR_THREE: 'Inspector 3',
    STRING_INSPECTOR_FOUR: 'Inspector 4',
    STRING_PACKER: 'Packer',
    STRING_NO_INSPECTOR: 'Inspector 1 Name Required.',
    STRING_NO_PACKER: 'Packer Name Required.',
    STRING_OPTIONAL: 'Optional',
    STRING_INSPECTORS: 'Inspector',

    //Dashboard
    STRING_CHANGE_PALLET: 'Change Pallet',

    ALERT_TITLE: {
      INFO: 'Info',
      ERROR: 'Error',
      FAILED: 'Failed',
      SUCCESS: 'Success',
      WENT_WRONG: 'Sorry, something went wrong',
      EXPIRED: 'Logout',
    },

    BTN: {
      OK: 'OK',
      CANCEL: 'Cancel',
      YES: 'Yes',
      NO: 'No',
      TRY_AGAIN: 'Try Again',
      CONTINUE: 'Continue',
      SUBMIT: 'Submit',
      CREATE: 'Create',
      UPDATE: 'Update',
      DONE: 'Done',
      CLOSE: 'Close',
      OKAY: 'Okay',
    },
  },
}